### ISSUE TITLE
SWFs compiled using Inline parameter throwing Invalid Code Length exception

### ISSUE THREAD

**Issue by vpmedia** [teesquared/flasturbate#1]
How to reproduce:
Compile a source code using `[Inline]` metadata and compiler parameter `-inline`

Exception after launching the SWF:

```
VerifyError: Error #1043: Invalid code_length=0.
```

**Comment by teesquared** [comment]
I haven't tested it with inline yet. If the SWF decompiles correctly with the disassembler RABCDAsm then we'll need to get the latest from them to support inlining.

**Comment by vpmedia** [comment]
Thanks for the response.
