### ISSUE TITLE
Updating the (dis)assembler

### ISSUE THREAD

**Issue by vpmedia** [teesquared/flasturbate#4]
Any chance for a merge from the original repo?

https://github.com/CyberShadow/RABCDAsm/commits/master

**Comment by teesquared** [comment]
I should give it a go. This may address the inline issue as well. I have a POB3 fix I am submitting soon so I may mess with a merge when I do that. Thanks for the suggestion and for reporting the issues.

**Comment by vpmedia** [comment]
Thanks!

**Comment by vpmedia** [comment]
And also thank you for releasing this project, far the best open-source SWF obfuscator out there.. ; )
